# Generated by Django 4.2.7 on 2026-07-31 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('door_open', 'Ouverture porte'), ('door_close', 'Fermeture porte'), ('boarding', 'Montée passager'), ('alighting', 'Descente passager'), ('stop_start', 'Début arrêt'), ('stop_end', 'Fin arrêt'), ('speeding', 'Excès de vitesse'), ('gps_lost', 'Perte GPS'), ('power_cut', 'Coupure alimentation'), ('sensor_failure', 'Panne capteur'), ('maintenance_due', 'Maintenance due')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='info', max_length=20)),
                ('count', models.IntegerField(default=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='trips.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', 'recorded_at'], name='events_even_vehicle_71b426_idx'), models.Index(fields=['type'], name='events_even_type_654a97_idx')],
            },
        ),
    ]
