# Generated by Django 4.2.7 on 2026-07-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('speeding', 'Excès de vitesse'), ('gps_lost', 'Perte GPS'), ('power_cut', 'Coupure alimentation'), ('sensor_failure', 'Panne capteur'), ('no_communication', 'Absence communication'), ('maintenance_due', 'Maintenance due'), ('capacity_exceeded', 'Capacité dépassée'), ('battery_low', 'Batterie faible')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('acknowledged', 'Reconnue'), ('resolved', 'Résolue')], default='new', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('suggested_action', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='alerts_aler_vehicle_d3d58a_idx'), models.Index(fields=['detected_at'], name='alerts_aler_detecte_80160a_idx')],
            },
        ),
    ]
