# Generated by Django 4.2.7 on 2026-07-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_passengers', models.IntegerField(default=0)),
                ('avg_daily_passengers', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operation_days', models.IntegerField(default=0)),
                ('trips_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('best_day', models.DateField(blank=True, null=True)),
                ('worst_day', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('vehicle', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_passengers', models.IntegerField(default=0)),
                ('avg_passengers', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_passengers', models.IntegerField(default=0)),
                ('trips_count', models.IntegerField(default=0)),
                ('stops_count', models.IntegerField(default=0)),
                ('operation_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('door_open_count', models.IntegerField(default=0)),
                ('boarding_count', models.IntegerField(default=0)),
                ('alighting_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
