# Generated by Django 4.2.7 on 2026-07-31 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('in_progress', 'En cours'), ('paused', 'En pause'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20)),
                ('trip_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('passengers_boarded', models.IntegerField(default=0)),
                ('passengers_alighted', models.IntegerField(default=0)),
                ('max_passengers_on_board', models.IntegerField(default=0)),
                ('avg_passengers', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stops_count', models.IntegerField(default=0)),
                ('total_stop_duration_sec', models.IntegerField(default=0)),
                ('route_geojson', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['vehicle', 'start_time'], name='trips_trip_vehicle_b9e12f_idx'), models.Index(fields=['status'], name='trips_trip_status_259ca6_idx')],
            },
        ),
    ]
