# Generated by Django 4.2.7 on 2026-07-31 23:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('taxi', 'Taxi'), ('truck', 'Camion'), ('van', 'Fourgon')], default='minibus', max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Essence'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], default='diesel', max_length=20)),
                ('capacity', models.IntegerField(default=15)),
                ('weight_kg', models.IntegerField(default=2000)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_policy', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('technical_control_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('maintenance', 'Maintenance'), ('offline', 'Hors ligne'), ('out_of_service', 'Hors service')], default='inactive', max_length=20)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20)),
                ('battery_level', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('signal_strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('last_latitude', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('last_longitude', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('last_speed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_address', models.CharField(blank=True, max_length=255, null=True)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_passengers', models.IntegerField(default=0)),
                ('current_passengers', models.IntegerField(default=0)),
                ('total_trips', models.IntegerField(default=0)),
                ('total_operation_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_interval_km', models.IntegerField(default=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_cell_threshold', models.DecimalField(decimal_places=2, default=35.0, max_digits=6)),
                ('passenger_weight_kg', models.IntegerField(default=70)),
                ('gps_update_interval_sec', models.IntegerField(default=5)),
                ('data_sync_interval_min', models.IntegerField(default=5)),
                ('max_speed_kmh', models.IntegerField(default=100)),
                ('stop_detection_threshold', models.IntegerField(default=30)),
                ('api_base_url', models.URLField(blank=True, default='http://localhost:8000/api')),
                ('is_offline_mode', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='vehicles.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner', 'status'], name='vehicles_ve_owner_i_d81e00_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_ve_registr_3774f3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['uuid'], name='vehicles_ve_uuid_1e5e99_idx'),
        ),
    ]
