# Generated by Django 4.2.7 on 2026-08-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='battery_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='battery_min_percent',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='connection_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='connection_timeout_min',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='gps_timeout_sec',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='max_stop_duration_min',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='speed_alert_delay_sec',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='speed_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='stop_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RestrictedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.PositiveIntegerField(default=500)),
                ('zone_type', models.CharField(choices=[('no_entry', "Interdiction d'entrée"), ('speed_limit', 'Limitation de vitesse'), ('custom', 'Personnalisée')], default='no_entry', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_zones', to='vehicles.vehicle')),
            ],
        ),
    ]
